name: Change Ad Blocking File Format

on:
  push:
    branches: [master]
    paths:
      - '.github/workflows/ad_block_file_format.yml'
  watch:
    types: started
  schedule:
    - cron: 5 12 * * *

jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - uses: actions/checkout@v2

      - name: Initialization environment
        run: sudo -E apt-get -qq install dos2unix

      - name: Download host file
        run: wget -q https://raw.githubusercontent.com/neodevpro/neodevhost/master/host_dnsmasq.conf -O host_dnsmasq.conf

      - name: Format file
        run: |
          dos2unix host_dnsmasq.conf
          sed -i '1,32d' host_dnsmasq.conf
          sed -i 's/0.0.0.0//g' host_dnsmasq.conf

      - name: Uplode to Aliyun oss
        env:
          ALI_AK: ${{ secrets.ALI_ACCESSKEY_ID_1 }}
          ALI_SK: ${{ secrets.ALI_ACCESSKEY_SECRET_1 }}
          OSS_ENDPOINT: ${{ secrets.OSS_ENDPOINT_1 }}
          OSS_BUCKET_URL: ${{ secrets.OSS_BUCKET_URL_1 }}
        run: |
          wget -q http://gosspublic.alicdn.com/ossutil/1.6.17/ossutil64 -O ossutil
          chmod +x ossutil
          ./ossutil -v
          ./ossutil config -e ${OSS_ENDPOINT} -i ${ALI_AK} -k ${ALI_SK} -L EN
          ./ossutil cp -f host_dnsmasq.conf ${OSS_BUCKET_URL}host_dnsmasq.conf
      - name: Uplode file
        uses: actions/upload-artifact@v2
        with:
          path: host_dnsmasq.conf
