name: Build Lesspass Server

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Cloen lesspass source code
      run: git clone https://github.com/lesspass/lesspass.git

    - name:Login Ali
      run: docker login $ALI_DOCKER_REGISTRY_LOGIN

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        docker-compose -v
        yarn -v
        pwd
        ls -l
