name: Build Lesspass Server

on:
  push:
    branches: [ master ]

env:
  UPLOAD_DIFF: false
  CONTAINER_URL: ${{ secrets.ALI_CONTAINER_URL }}

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Cloen lesspass source code
      run: git clone https://github.com/lesspass/lesspass.git

    - name: Load custom configuration
      env:
        CONTAINER_DOMAIN: ${{ secrets.ALI_CONTAINER_DOMAIN }}
        CONTAINER_PATH: ${{ secrets.ALI_CONTAINER_PATH }}
      run: |
        chmod +x diy.sh
        mv diy.sh lesspass/
        cd lesspass/
        ./diy.sh
        git diff >> "$GITHUB_WORKSPACE/diff.txt"
        cat "$GITHUB_WORKSPACE/diff.txt"
        
    - name: Upload diff file
      uses: actions/upload-artifact@v2
      if: env.UPLOAD_DIFF == 'true' && !cancelled()
      with:
        name: diff
        path: diff.txt

    - name: Build containers
      run: |
        cd lesspass/containers/
        wget https://github.com/docker/compose/releases/download/1.26.2/docker-compose-Linux-x86_64 -O docker-compose
        chmod +x docker-compose
        ./docker-compose -v
        ./docker-compose build

    - name: Push containers
      env:
        ALI_LOGIN: ${{ secrets.ALI_DOCKER_REGISTRY_LOGIN }}
      run: |
        docker images
        docker login $ALI_LOGIN
        docker push $CONTAINER_URL/lesspass-frontend
        docker push $CONTAINER_URL/lesspass-backend
