name: Test

on:
  push:
    branches: [master]
    paths:
      - '.github/workflows/test.yml'

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: test
        env:
          CONTAINER_DOMAIN: ${{ secrets.ALI_CONTAINER_DOMAIN }}
          CONTAINER_PATH: ${{ secrets.ALI_CONTAINER_PATH }}
          DEFAULT_FROM_EMAIL: ${{ secrets.DEFAULT_FROM_EMAIL }}
          EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
          EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
          EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
          CONTAINER_URL: ${{ secrets.ALI_CONTAINER_URL }}
        run: echo "${CONTAINER_DOMAIN} ${CONTAINER_PATH} ${DEFAULT_FROM_EMAIL} ${EMAIL_HOST} ${EMAIL_HOST_USER} ${EMAIL_HOST_PASSWORD} ${CONTAINER_URL}" > 1.txt
      
      - name: uplode
        uses: actions/upload-artifact@v2
        with:
            path: '1.txt'

