name: Test

on:
  push:
    branches: [master]
    paths:
      - '.github/workflows/test.yml'

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: test
        env:
          CONTAINER_DOMAIN: ${{ secrets.ALI_CONTAINER_DOMAIN_1 }}
        run: echo "${CONTAINER_DOMAIN}" > 1.txt
      
      - name: uplode
        uses: actions/upload-artifact@v2
        with:
            path: '1.txt'

