name: Test

on:
  push:
    branches: [master]
    paths:
      - '.github/workflows/test.yml'

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Create local changes
        run: |
          cd $GITHUB_WORKSPACE
          echo "$(date +'%Y-%m-%d %H:%M:%S')" > test.txt

      - name: Commit files
        run: |
          git config --local user.email "out@qxzg.xyz"
          git config --local user.name "GitHub Action"
          git commit -m "testing push" -a
          git push --quiet "https://${{ secrets.ACCESS_TOKEN }}@github.com/qxzg/Actions.git" master:master